version: "3.1"
services:
  web_phptraining:
    build: .
    ports:
     - "80:80"
    links:
     - db_phptraining
    volumes:
     - ./app:/app

  db_phptraining:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
      - "8889:3306"

  pma_phptraining:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      PMA_HOST: db_phptraining
    ports:
      - "9001:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "9002:8025"